name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # ✅ Gradle 캐시 적용 (속도 향상)
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Set gradlew permissions
      run: chmod +x ./gradlew

    # ✅ 테스트 생략하여 빌드 속도 개선
    - name: Build with Gradle (skip tests)
      run: ./gradlew build -x test

    - name: Set SSH key permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 54.180.97.91 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: scp build/libs/*.jar ubuntu@54.180.97.91:~/app

    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@54.180.97.91 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/app/myDevops-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &
        EOF
